[project]
name = "Additive combinatorics: Sidon sets and N(h,k) bounds"
frontier_id = "vfr_496956067dc5ad79"
compiled_at = "2026-05-09T19:20:04Z"
description = ""
compiler = "vela/0.75.0"
papers_processed = 0
